export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILUER = 'LOGIN_USER_FAILUER';

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILUER = 'REGISTER_USER_FAILUER';

export const AUTH_CHECK = 'AUTH_CHECK';

export const LOGOUT = 'LOGOUT';
